version: 2.1

workflows:
  build_plugin:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    # For more details on extending your workflow,
    # see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
    jobs:
      - pants-checks
      - build-plugin-wheel

executors:
  plugin-executor:
    docker:
    - image: cimg/python:3.9.13
      environment:
          PANTS_CONFIG_FILES: pants.ci.toml

commands:
  setup-pants:
    description: "Setup pants build tool"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0-pants_cache-{{ arch }}--{{ .Branch }}-{{ .Revision }}
            - v0-pants_cache-{{ arch }}--{{ .Branch }}
            - v0-pants_cache-{{ arch }}
      - run:
          name: setup distutils
          command: sudo apt-get update && sudo apt-get install python3-distutils
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: setup_pants
          command: ./pants --version
  save-pants-cache:
    description: "Store intermediate pants build artifacts and rule results"
    steps:
      - save_cache:
          key: v0-pants_cache-{{ arch }}--{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.cache/pants/setup
            - ~/.cache/pants/named_cache
            - ~/.cache/pants/lmdb_caches

jobs:
  pants-checks:
    executor: plugin-executor
    steps:
      - setup-pants
      - run:
          command: './pants update-build-files --check ::'
      - run:
          command: './pants lint ::'
      - save-pants-cache
  build-plugin-wheel:
    executor: plugin-executor
    steps:
      - setup-pants
      - run:
          name: run tests
          command: './pants test ::'
      - run:
          name: Build package
          command: ./pants package pants_plugins/sendwave/pants_docker:pants_docker
      - save-pants-cache
      - store_artifacts:
          path: ./dist/
